###
POST http://localhost:8000/contacts
Accept: application/json
Content-Type: application/json
Authorization:{{token}}

{
  "name"    : "유재영",
  "email"   : "Jaeyoung@wisoft.io",
  "phone"   : "010-1234-5678",
  "address" : "대전광역시 유성구 덕명동"
}

> {%
    client.global.set("addressId", response.body._id);
%}

###
GET http://localhost:8000/contacts
Accept: application/json
Authorization: {{token}}

###
DELETE http://localhost:8000/contacts/{{addressId}}
Accept: application/json
Authorization: {{token}}

###
PATCH http://localhost:8000/contacts/{{addressId}}
Accept: application/json
Content-Type: application/json
Authorization:{{token}}

{
  "address" : "한밭대학교 N5동 WiSoft 랩실"
}