###
GET http://localhost:8000/api/users/jwt/6419e1f0733cfde78433ccd5
Accept: application/json

###
POST http://localhost:8000/api/users
Accept: application/json
Content-Type: application/json

{
  "userName": "Jae0",
  "address": "Daejeon-si Yuseong-gu Hakha-dong",
  "phoneNumber": "010-xxxx-xxxx",
  "email": "Jae0@wisoft.io"
}

###
DELETE http://localhost:8000/api/users/641abc39cd31d82b3753f8dd

###
PATCH http://localhost:8000/api/users/641af66e58e97679c3272bb9
Authorization: "yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiSmFlMCIsImVtYWlsIjoiSmFlMEB3aXNvZnQuaW8ifSwiaWF0IjoxNjc5NDg4NjIyLCJleHAiOjE2Nzk0ODg5MjJ9.cwb_5gheSlCpZ52ujlBhxhbDMeWXbj4BKG15aP0YGTc"
Accept: application/json
Content-Type: application/json

{
  "email": "Jaeyoung1111@wisoft.io"
}