###
POST http://localhost:8000/api/users
Accept: application/json
Content-Type: application/json

{
  "email": "Jaeyoung@wisoft.io",
  "password": "nodejs",
  "userName": "Jaeyoung",
  "nickName": "Jackyoung"
}

###
POST http://localhost:8000/api/users
Accept: application/json
Content-Type: application/json

{
  "email": "JaeOne@wisoft.io",
  "password": "nodejs",
  "userName": "JaeOne",
  "nickName": "Jack"
}


###
GET http://localhost:8000/api/users
Accept: application/json


###
PATCH http://localhost:8000/api/users
Accept: application/json
Content-Type: application/json

{
  "email": "Jaeyoung@wisoft.io",
  "password": "nodejs",
  "nickName": "patchedNickname"
}


###
DELETE  http://localhost:8000/api/users
Accept: application/json
Content-Type: application/json

{
  "email": "Jaeyoung@wisoft.io",
  "password": "nodejs"
}